### ISSUE TITLE
scale-length of chemical mixing in molecular clouds

### ISSUE THREAD

**Issue by smoh** [smoh/KronosKrios#11]
> For chemical inhomogeneity, are there any theoretical studies that suggest
a scale-length for chemical mixing? I feel like we need to comment on this,
too -- maybe Eve has an idea? I'm happy to follow up with her on this if it would be useful.

**Comment by adrn** [comment]
If you want to add a reference that suggests fast mixing: https://ui.adsabs.harvard.edu/#abs/2014Natur.513..523F/abstract

```
@ARTICLE{2014Natur.513..523F,
   author = {{Feng}, Y. and {Krumholz}, M.~R.},
    title = "{Early turbulent mixing as the origin of chemical homogeneity in open star clusters}",
  journal = {\nat},
archivePrefix = "arXiv",
   eprint = {1408.6543},
     year = 2014,
    month = sep,
   volume = 513,
    pages = {523-525},
      doi = {10.1038/nature13662},
   adsurl = {http://adsabs.harvard.edu/abs/2014Natur.513..523F},
  adsnote = {Provided by the SAO/NASA Astrophysics Data System}
}
```
